curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/tvupjwpopc/01.%20Hell%20On%20Earth.mp3' > '01. Hell On Earth.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/hxdlctfvuo/02.%20Cultist%20Base.mp3' > '02. Cultist Base.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/vpeduimdkx/03.%20Blood%20Harvesting.mp3' > '03. Blood Harvesting.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/kzrqmnfgnj/04.%20Soul%20Extraction.mp3' > '04. Soul Extraction.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/fdafglixnf/05.%20BFG%20Division%202020.mp3' > '05. BFG Division 2020.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/tsrwirpoeg/06.%20Metal%20Hell.mp3' > '06. Metal Hell.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/rhxwidyysy/07.%20Paradise%20Lost.mp3' > '07. Paradise Lost.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/adaeefkctv/08.%20Urdak.mp3' > '08. Urdak.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/yqybtifqma/09.%20The%20Doom%20Hunter.mp3' > '09. The Doom Hunter.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/kzwafnrtcr/10.%20Infiltrate%20the%20Cult.mp3' > '10. Infiltrate the Cult.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/luybvcdwxa/11.%20Cultist%20Prayer.mp3' > '11. Cultist Prayer.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/hxqrvcoyfj/12.%20Demonic%20Corruption%20.mp3' > '12. Demonic Corruption .mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/ydwupvyhqc/13.%20Maykr%20Drones.mp3' > '13. Maykr Drones.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/vzdqtaexxo/14.%20The%20Khan%20Maykr%20%28Chad%20Mossholder%20remix%29.mp3' > '14. The Khan Maykr (Chad Mossholder remix).mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/bptyqljqxt/15.%20Deag%20Ranak.mp3' > '15. Deag Ranak.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/edzwrhnoth/16.%20Mars%20Core.mp3' > '16. Mars Core.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/ekilxbkbeq/17.%20Deag%20Nilox%20-%20First%20Priest%20Death.mp3' > '17. Deag Nilox - First Priest Death.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/guldfjzjef/18.%20The%20Icon%20of%20Sin.mp3' > '18. The Icon of Sin.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/nutyxayzeb/19.%20Phobos%20Space.mp3' > '19. Phobos Space.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/jascypojdt/20.%20A%20Slayer%20City.mp3' > '20. A Slayer City.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/znczhgkiao/21.%20The%20Super%20Gore%20Nest.mp3' > '21. The Super Gore Nest.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/blivxsjmjb/22.%20The%20Only%20Thing%20They%20Fear%20Is%20You.mp3' > '22. The Only Thing They Fear Is You.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/qynmlhmyxj/23.%20Asteroids%20and%20Rockets.mp3' > '23. Asteroids and Rockets.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/qwyetaintv/24.%20You%20Can_t%20Just%20Shoot%20A%20Hole%20Into%20The%20surface%20of%20Mars.mp3' > '24. You Can_t Just Shoot A Hole Into The surface of Mars.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/tedoestsqt/25.%20Doom%20Hunted.mp3' > '25. Doom Hunted.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/kwkevcgqsb/26.%20Blood%20Sacrifice.mp3' > '26. Blood Sacrifice.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/mntfekmqgt/27.%20Welcome%20Home%20Great%20Slayer.mp3' > '27. Welcome Home Great Slayer.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/hwutixhiwg/28.%20Prayer%20of%20the%20Diminished.mp3' > '28. Prayer of the Diminished.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/pizgtlwrga/29.%20Gladiator%20Boss.mp3' > '29. Gladiator Boss.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/psqmlyvtox/30.%20Beast%20of%20the%20Arena.mp3' > '30. Beast of the Arena.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/yywihsueuv/31.%20Fortress%20of%20Doom%20-%20Chad%20Mossholder.mp3' > '31. Fortress of Doom - Chad Mossholder.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/kijnpbefoo/32.%20Revenant%20Possession.mp3' > '32. Revenant Possession.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/ppszqdfriv/33.%20Usuper%20Gore.mp3' > '33. Usuper Gore.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/bcqtnturum/34.%20Sinister.mp3' > '34. Sinister.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/mxkbrynspu/35.%20Super%20Shotgun%20Reunion.mp3' > '35. Super Shotgun Reunion.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/vxeohorsso/36.%20The%20Baron%20of%20Hell.mp3' > '36. The Baron of Hell.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/vsnyauqtrm/37.%20Doomed%20Hunter.mp3' > '37. Doomed Hunter.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/cpceztwlor/38.%20Command%20and%20Control.mp3' > '38. Command and Control.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/myoucnfuho/39.%20BFG%2010k.mp3' > '39. BFG 10k.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/nzvgjzjwml/40.%20Sams%20Base.mp3' > '40. Sams Base.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/kxxrevkzyb/41.%20Phobos%20Base.mp3' > '41. Phobos Base.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/kuuebgulgi/42.%20Acquiring%20the%20BFG.mp3' > '42. Acquiring the BFG.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/ewcyebvwdy/43.%20Heart%20of%20the%20Beast.mp3' > '43. Heart of the Beast.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/pkzqczmarf/44.%20Consumption.mp3' > '44. Consumption.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/xnwpklsdle/45.%20Bio-organic%20Continuum%20Gate.mp3' > '45. Bio-organic Continuum Gate.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/aijrygvihe/46.%20Massive%20Demonic%20Presence.mp3' > '46. Massive Demonic Presence.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/kxoloinutt/47.%20Armored%20Response%20Coalition%20.mp3' > '47. Armored Response Coalition .mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/pjzvninaev/48.%20Kalibas%20the%20Sightless%20Judge.mp3' > '48. Kalibas the Sightless Judge.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/mizbpcpbau/49.%20S.O.S.%20from%20Earth.mp3' > '49. S.O.S. from Earth.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/gnsiroctng/50.%20Barging%20In.mp3' > '50. Barging In.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/uaaeimjfpv/51.%20Taras%20Nabad.mp3' > '51. Taras Nabad.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/fxilxywudt/52.%20King%20Novik.mp3' > '52. King Novik.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/buxkmhznkc/53.%20The%20Khan%20Maykr%20%28Chad%20Mossholder%20Remix%29.mp3' > '53. The Khan Maykr (Chad Mossholder Remix).mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/wdjuydzxye/54.%20Meathook.mp3' > '54. Meathook.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/bqfbfzjwrh/55.%20Eternal%20Prophecy.mp3' > '55. Eternal Prophecy.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/temdqsgcdm/56.%20The%20Betrayer.mp3' > '56. The Betrayer.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/qlqjrqsduj/57.%20Doom%20Eternal.mp3' > '57. Doom Eternal.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/msgcregenu/58.%20End%20of%20Level.mp3' > '58. End of Level.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/nikhvpfcte/59.%20Final%20Sin%20-%20Sandy%20City.mp3' > '59. Final Sin - Sandy City.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/qybqyoklyc/60.%20Prototype%20Music.mp3' > '60. Prototype Music.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/aowchffqnp/The%20Ancient%20Gods%2001.%20Atlantica.mp3' > 'The Ancient Gods 01. Atlantica.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/xarbfbfvse/The%20Ancient%20Gods%2002.%20Blood%20Swamps.mp3' > 'The Ancient Gods 02. Blood Swamps.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/bndebnocmk/The%20Ancient%20Gods%2003.%20The%20Trial%20of%20Maligog.mp3' > 'The Ancient Gods 03. The Trial of Maligog.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/syqqzvfjlr/The%20Ancient%20Gods%2004.%20The%20Holt.mp3' > 'The Ancient Gods 04. The Holt.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/ixehbleflu/The%20Ancient%20Gods%2005.%20Shady%20Hayden.mp3' > 'The Ancient Gods 05. Shady Hayden.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/hqrhetdnmw/The%20Ancient%20Gods%2006.%20Sinister%27s%20Gate.mp3' > 'The Ancient Gods 06. Sinisters Gate.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/omccbaaaoj/The%20Ancient%20Gods%2007.%20The%20World%20Spear.mp3' > 'The Ancient Gods 07. The World Spear.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/adpjbmcgrt/The%20Ancient%20Gods%2008.%20Reclaimed%20Earth.mp3' > 'The Ancient Gods 08. Reclaimed Earth.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/ufrgyisbqu/The%20Ancient%20Gods%2009.%20Immora.mp3' > 'The Ancient Gods 09. Immora.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/jhmjlvqoai/The%20Ancient%20Gods%2010.%20Davoth.mp3' > 'The Ancient Gods 10. Davoth.mp3'
curl -k 'https://vgmsite.com/soundtracks/doom-eternal-complete-game-soundtrack/rqrrbdyqxd/The%20Ancient%20Gods%2011.%20may%20we%20need%20you%20again..mp3' > 'The Ancient Gods 11. may we need you again..mp3'
