curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/01.%2520Hell%2520On%2520Earth.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/02.%2520Cultist%2520Base.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/03.%2520Blood%2520Harvesting.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/04.%2520Soul%2520Extraction.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/05.%2520BFG%2520Division%25202020.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/06.%2520Metal%2520Hell.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/07.%2520Paradise%2520Lost.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/08.%2520Urdak.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/09.%2520The%2520Doom%2520Hunter.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/10.%2520Infiltrate%2520the%2520Cult.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/11.%2520Cultist%2520Prayer.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/12.%2520Demonic%2520Corruption%2520.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/13.%2520Maykr%2520Drones.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/14.%2520The%2520Khan%2520Maykr%2520%2528Chad%2520Mossholder%2520remix%2529.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/15.%2520Deag%2520Ranak.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/16.%2520Mars%2520Core.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/17.%2520Deag%2520Nilox%2520-%2520First%2520Priest%2520Death.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/18.%2520The%2520Icon%2520of%2520Sin.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/19.%2520Phobos%2520Space.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/20.%2520A%2520Slayer%2520City.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/21.%2520The%2520Super%2520Gore%2520Nest.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/22.%2520The%2520Only%2520Thing%2520They%2520Fear%2520Is%2520You.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/23.%2520Asteroids%2520and%2520Rockets.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/24.%2520You%2520Can_t%2520Just%2520Shoot%2520A%2520Hole%2520Into%2520The%2520surface%2520of%2520Mars.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/25.%2520Doom%2520Hunted.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/26.%2520Blood%2520Sacrifice.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/27.%2520Welcome%2520Home%2520Great%2520Slayer.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/28.%2520Prayer%2520of%2520the%2520Diminished.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/29.%2520Gladiator%2520Boss.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/30.%2520Beast%2520of%2520the%2520Arena.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/31.%2520Fortress%2520of%2520Doom%2520-%2520Chad%2520Mossholder.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/32.%2520Revenant%2520Possession.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/33.%2520Usuper%2520Gore.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/34.%2520Sinister.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/35.%2520Super%2520Shotgun%2520Reunion.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/36.%2520The%2520Baron%2520of%2520Hell.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/37.%2520Doomed%2520Hunter.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/38.%2520Command%2520and%2520Control.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/39.%2520BFG%252010k.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/40.%2520Sams%2520Base.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/41.%2520Phobos%2520Base.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/42.%2520Acquiring%2520the%2520BFG.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/43.%2520Heart%2520of%2520the%2520Beast.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/44.%2520Consumption.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/45.%2520Bio-organic%2520Continuum%2520Gate.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/46.%2520Massive%2520Demonic%2520Presence.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/47.%2520Armored%2520Response%2520Coalition%2520.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/48.%2520Kalibas%2520the%2520Sightless%2520Judge.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/49.%2520S.O.S.%2520from%2520Earth.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/50.%2520Barging%2520In.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/51.%2520Taras%2520Nabad.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/52.%2520King%2520Novik.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/53.%2520The%2520Khan%2520Maykr%2520%2528Chad%2520Mossholder%2520Remix%2529.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/54.%2520Meathook.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/55.%2520Eternal%2520Prophecy.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/56.%2520The%2520Betrayer.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/57.%2520Doom%2520Eternal.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/58.%2520End%2520of%2520Level.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/59.%2520Final%2520Sin%2520-%2520Sandy%2520City.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/60.%2520Prototype%2520Music.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/The%2520Ancient%2520Gods%252001.%2520Atlantica.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/The%2520Ancient%2520Gods%252002.%2520Blood%2520Swamps.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/The%2520Ancient%2520Gods%252003.%2520The%2520Trial%2520of%2520Maligog.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/The%2520Ancient%2520Gods%252004.%2520The%2520Holt.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/The%2520Ancient%2520Gods%252005.%2520Shady%2520Hayden.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/The%2520Ancient%2520Gods%252006.%2520Sinister%2527s%2520Gate.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/The%2520Ancient%2520Gods%252007.%2520The%2520World%2520Spear.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/The%2520Ancient%2520Gods%252008.%2520Reclaimed%2520Earth.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/The%2520Ancient%2520Gods%252009.%2520Immora.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/The%2520Ancient%2520Gods%252010.%2520Davoth.mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4
curl -k -s https://downloads.khinsider.com/game-soundtracks/album/doom-eternal-complete-game-soundtrack/The%2520Ancient%2520Gods%252011.%2520may%2520we%2520need%2520you%2520again..mp3 | grep 'vgmsite' | grep href | cut -d '"' -f4