curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/xwpktuvj/01-%3D-nine%20thou%20%28superstars%20remix%29.mp3 >'01. nine thou (superstars remix).mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/fvimcsfd/02-%3D-do%20ya%20thang.mp3 >'02. do ya thang.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/jbquiuwx/03-%3D-i%20am%20rock.mp3 >'03. i am rock.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/fppsvtuv/04-%3D-in%20a%20hood%20near%20you.mp3 >'04. in a hood near you.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/xxmstshh/05-%3D-let%27s%20move.mp3 >'05. lets move.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/potutxbu/06-%3D-sets%20go%20up.mp3 >'06. sets go up.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/dcwlndnr/07-%3D-fired%20up.mp3 >'07. fired up.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/zvinakhy/08-%3D-b-side%20wins%20again%20feat.%20chuck%20d.mp3 >'08. b-side wins again feat. chuck d.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/qtutzcdz/09-%3D-shapeshifter.mp3 >'09. shapeshifter.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/lxgqniie/10-%3D-tilted.mp3 >'10. tilted.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/zqliptqv/11-%3D-feed%20the%20addiction.mp3 >'11. feed the addiction.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/wwbpfhvs/12-%3D-one%20good%20reason.mp3 >'12. one good reason.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/kosvybgk/13-%3D-we%20control.mp3 >'13. we control.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/tktskiqp/14-%3D-skinnyman.mp3 >'14. skinnyman.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/yxnxqzgz/15-%3D-barrier%20break.mp3 >'15. barrier break.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/ycahquij/16-%3D-decadence.mp3 >'16. decadence.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/hmvonbyw/17-%3D-%20The%20Prodigy%20-%20you%27ll%20be%20under%20my%20wheels.mp3 >'17.  The Prodigy - youll be under my wheels.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/mgmjxwgf/18-%3D-tao%20of%20the%20machine%20%28scott%20humphrey%27s%20remix%29.mp3 >'18. tao of the machine (scott humphreys remix).mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/aactueee/19-%3D-you%20must%20follow%20%28evol%20intent%20vip%29.mp3 >'19. you must follow (evol intent vip).mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/fpxsemac/20-%3D-blood%20and%20thunder.mp3 >'20. blood and thunder.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/twqlzhsy/21-%3D-broken%20sword.mp3 >'21. broken sword.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/mobgmdtp/22-%3D-hand%20of%20blood.mp3 >'22. hand of blood.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/tylnqoky/23-%3D-the%20mann.mp3 >'23. the mann.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/xwsmimcf/24-%3D-blinded%20in%20chains.mp3 >'24. blinded in chains.mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/whleccmj/25-%3D-feels%20just%20like%20it%20should%20%28timo%20maas%20remix%29.mp3 >'25. feels just like it should (timo maas remix).mp3'
curl -sk https://vgmsite.com/soundtracks/need-for-speed-most-wanted/qvrqeutb/26-%3D-most%20wanted%20mash%20up.mp3 >'26. most wanted mash up.mp3'